source 'https://rubygems.org'

gem 'fluentd', '~> 1.9', '>= 1.9.0'
gem 'fluent-plugin-concat', '~> 2.4'
gem 'fluent-plugin-kubernetes_metadata_filter', '~> 2.4'
gem 'fluent-plugin-elasticsearch', '~> 4.0', '>= 4.0.0'
gem 'elasticsearch-xpack', '~> 7.4', '>= 7.4.0'
gem 'fluent-plugin-systemd', '~> 1.0', '>= 1.0.2'
gem 'fluent-plugin-detect-exceptions', '~> 0.0.12'
gem 'fluent-plugin-prometheus', '~> 1.7', '>= 1.7.0'
gem 'fluent-plugin-multi-format-parser', '~> 1.0'
gem 'fluent-plugin-rewrite-tag-filter', '~> 2.2'
gem 'fluent-plugin-record-modifier', '~> 2.1', '>= 2.1.0'
gem 'fluent-plugin-http-healthcheck', '~> 0.1.0'
gem 'oj', '~> 3.9', '>= 3.9.2'
