source 'https://rubygems.org'

gem 'fluentd', '~> 1.7', '>= 1.7.3'
gem 'fluent-plugin-concat', '~> 2.4'
gem 'fluent-plugin-kubernetes_metadata_filter', '~> 2.4'
gem 'fluent-plugin-elasticsearch', '~> 3.5', '>= 3.5.5'
gem 'fluent-plugin-systemd', '~> 1.0', '>= 1.0.2'
gem 'fluent-plugin-detect-exceptions', '~> 0.0.12'
gem 'fluent-plugin-prometheus', '~> 1.6', '>= 1.6.1'
gem 'fluent-plugin-multi-format-parser', '~> 1.0'
gem 'fluent-plugin-rewrite-tag-filter', '~> 2.2'
gem 'fluent-plugin-record-modifier', '~> 2.0', '>= 2.0.1'
gem 'fluent-plugin-http-healthcheck', '~> 0.1.0'
gem 'oj', '~> 3.9', '>= 3.9.2'
